services:
  mysql:
    image: mysql:latest
    container_name: mysql_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: auth
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  msql: